language: node_js
node_js:
- stable
- lts/*

cache:
  directories:
    node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d

install:
  npm install # done by default

script:
  npm test # done by default
  npm run build

deploy:
  provider: gae
  edge: true
  keyfile: client_secret.json
  project: my-react-application-275913 # project ID
